// Copyright (C) 2026 caicoders (https://github.com/caicoders)
// SPDX-License-Identifier: AGPL-3.0-or-later

package config

import (
	"fmt"
	"os"
	"path/filepath"

	"gopkg.in/yaml.v3"
)

const DefaultConfigFile = "getares.yaml"

// Role constants
const (
	RoleCoordinator = "coordinator"
	RoleWorker      = "worker"
	RoleBoth        = "both"
)

type Config struct {
	Role        string      `yaml:"role"`
	NodeID      string      `yaml:"node_id"`
	Coordinator CoordConfig `yaml:"coordinator,omitempty"`
	Worker      WorkerConfig `yaml:"worker,omitempty"`
}

type CoordConfig struct {
	GRPCAddr string `yaml:"grpc_addr"`
	HTTPAddr string `yaml:"http_addr"`
}

type WorkerConfig struct {
	Listen      string `yaml:"listen"`
	LlamaPort   int    `yaml:"llama_port"`
	ModelPath   string `yaml:"model_path"`
	ModelID     string `yaml:"model_id"`
	Coordinator string `yaml:"coordinator"`
}

// Load reads getares.yaml from the current directory.
func Load() (*Config, error) {
	data, err := os.ReadFile(DefaultConfigFile)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, fmt.Errorf("getares.yaml not found — run 'getares init' first")
		}
		return nil, fmt.Errorf("reading %s: %w", DefaultConfigFile, err)
	}

	var cfg Config
	if err := yaml.Unmarshal(data, &cfg); err != nil {
		return nil, fmt.Errorf("parsing %s: %w", DefaultConfigFile, err)
	}
	return &cfg, nil
}

// Save writes the config to getares.yaml in the current directory.
func Save(cfg *Config) error {
	// Expand ~ in model path before saving
	if cfg.Worker.ModelPath != "" {
		home, err := os.UserHomeDir()
		if err == nil {
			if len(cfg.Worker.ModelPath) >= 2 && cfg.Worker.ModelPath[:2] == "~/" {
				cfg.Worker.ModelPath = filepath.Join(home, cfg.Worker.ModelPath[2:])
			}
		}
	}

	data, err := yaml.Marshal(cfg)
	if err != nil {
		return fmt.Errorf("serializing config: %w", err)
	}

	header := []byte("# Getares configuration — generated by 'getares init'\n# Edit manually or re-run 'getares init' to reconfigure.\n\n")
	return os.WriteFile(DefaultConfigFile, append(header, data...), 0644)
}
